services:
  app:
    image: food
    build:
      context: .
    container_name: food
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/food
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_PROFILES_PASSWORD=root
#      - SERVER_PORT=8090

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=food
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
